language: ruby
script: "bundle exec rake test:units"
sudo: false
cache: bundler

rvm:
- 2.7
- 2.6
- 2.5

gemfile:
- gemfiles/Gemfile.rails60
- gemfiles/Gemfile.latest-release
- gemfiles/Gemfile.shopify

matrix:
  include:
    - rvm: 2.5
      gemfile: gemfiles/Gemfile.rails-edge

before_install:
  - gem update bundler
