name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  build:
    name: Ruby ${{ matrix.version }} ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      matrix:
        version:
          - 2.5
          - 2.6
          - 2.7
        gemfile:
          - gemfiles/Gemfile.rails60
          - gemfiles/Gemfile.latest-release
          - gemfiles/Gemfile.shopify
          - gemfiles/Gemfile.rails-edge
        # exclude:
        #   - version: 2.7
        #     gemfile: <Gemfile> to exclude for Ruby Version above
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true

      - name: Test
        run: bundle exec rake test

      # - name: Lint
      #   run: bundle exec rubocop --fail-fast
      #   working-directory: ./gems/offsite_payments
